//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sdi3_204.Cli_NET.SeatsService {
    
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ejb.impl.business.sdi.uo/")]
    public partial class EntityNotFoundException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ejb.impl.business.sdi.uo/")]
    public partial class seat : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string commentField;
        
        private seatStatus statusField;
        
        private bool statusFieldSpecified;
        
        private long tripIdField;
        
        private bool tripIdFieldSpecified;
        
        private long userIdField;
        
        private bool userIdFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
                this.RaisePropertyChanged("comment");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public seatStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("statusSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long tripId {
            get {
                return this.tripIdField;
            }
            set {
                this.tripIdField = value;
                this.RaisePropertyChanged("tripId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tripIdSpecified {
            get {
                return this.tripIdFieldSpecified;
            }
            set {
                this.tripIdFieldSpecified = value;
                this.RaisePropertyChanged("tripIdSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("userId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool userIdSpecified {
            get {
                return this.userIdFieldSpecified;
            }
            set {
                this.userIdFieldSpecified = value;
                this.RaisePropertyChanged("userIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ejb.impl.business.sdi.uo/")]
    public enum seatStatus {
        
        /// <comentarios/>
        ADMITIDO,
        
        /// <comentarios/>
        EXCLUIDO,
        
        /// <comentarios/>
        PENDIENTE,
        
        /// <comentarios/>
        SIN_PLAZA,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ejb.impl.business.sdi.uo/")]
    public partial class EntityAlreadyExistsException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ejb.impl.business.sdi.uo/", ConfigurationName="SeatsService.SeatsService")]
    public interface SeatsService {
        
        // CODEGEN: El parámetro 'arg0' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(sdi3_204.Cli_NET.SeatsService.EntityNotFoundException), Action="", Name="EntityNotFoundException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        sdi3_204.Cli_NET.SeatsService.cancelSeatResponse cancelSeat(sdi3_204.Cli_NET.SeatsService.cancelSeat request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        sdi3_204.Cli_NET.SeatsService.findByTripResponse findByTrip(sdi3_204.Cli_NET.SeatsService.findByTrip request);
        
        // CODEGEN: El parámetro 'arg0' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(sdi3_204.Cli_NET.SeatsService.EntityAlreadyExistsException), Action="", Name="EntityAlreadyExistsException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        sdi3_204.Cli_NET.SeatsService.seatsToUpdateResponse seatsToUpdate(sdi3_204.Cli_NET.SeatsService.seatsToUpdate request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        sdi3_204.Cli_NET.SeatsService.findApplicationByTripResponse findApplicationByTrip(sdi3_204.Cli_NET.SeatsService.findApplicationByTrip request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(sdi3_204.Cli_NET.SeatsService.EntityNotFoundException), Action="", Name="EntityNotFoundException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        sdi3_204.Cli_NET.SeatsService.findApplicationResponse findApplication(sdi3_204.Cli_NET.SeatsService.findApplication request);
        
        // CODEGEN: El parámetro 'arg0' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(sdi3_204.Cli_NET.SeatsService.EntityAlreadyExistsException), Action="", Name="EntityAlreadyExistsException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        sdi3_204.Cli_NET.SeatsService.requestResponse request(sdi3_204.Cli_NET.SeatsService.request request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(sdi3_204.Cli_NET.SeatsService.EntityNotFoundException), Action="", Name="EntityNotFoundException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        sdi3_204.Cli_NET.SeatsService.findByUserAndTripResponse findByUserAndTrip(sdi3_204.Cli_NET.SeatsService.findByUserAndTrip request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelSeat", WrapperNamespace="http://ejb.impl.business.sdi.uo/", IsWrapped=true)]
    public partial class cancelSeat {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ejb.impl.business.sdi.uo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public sdi3_204.Cli_NET.SeatsService.seat arg0;
        
        public cancelSeat() {
        }
        
        public cancelSeat(sdi3_204.Cli_NET.SeatsService.seat arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelSeatResponse", WrapperNamespace="http://ejb.impl.business.sdi.uo/", IsWrapped=true)]
    public partial class cancelSeatResponse {
        
        public cancelSeatResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findByTrip", WrapperNamespace="http://ejb.impl.business.sdi.uo/", IsWrapped=true)]
    public partial class findByTrip {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ejb.impl.business.sdi.uo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        public findByTrip() {
        }
        
        public findByTrip(long arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findByTripResponse", WrapperNamespace="http://ejb.impl.business.sdi.uo/", IsWrapped=true)]
    public partial class findByTripResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ejb.impl.business.sdi.uo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public sdi3_204.Cli_NET.SeatsService.seat[] @return;
        
        public findByTripResponse() {
        }
        
        public findByTripResponse(sdi3_204.Cli_NET.SeatsService.seat[] @return) {
            this.@return = @return;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ejb.impl.business.sdi.uo/")]
    public partial class application : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long tripIdField;
        
        private bool tripIdFieldSpecified;
        
        private long userIdField;
        
        private bool userIdFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long tripId {
            get {
                return this.tripIdField;
            }
            set {
                this.tripIdField = value;
                this.RaisePropertyChanged("tripId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tripIdSpecified {
            get {
                return this.tripIdFieldSpecified;
            }
            set {
                this.tripIdFieldSpecified = value;
                this.RaisePropertyChanged("tripIdSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("userId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool userIdSpecified {
            get {
                return this.userIdFieldSpecified;
            }
            set {
                this.userIdFieldSpecified = value;
                this.RaisePropertyChanged("userIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="seatsToUpdate", WrapperNamespace="http://ejb.impl.business.sdi.uo/", IsWrapped=true)]
    public partial class seatsToUpdate {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ejb.impl.business.sdi.uo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("arg0", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public sdi3_204.Cli_NET.SeatsService.application[] arg0;
        
        public seatsToUpdate() {
        }
        
        public seatsToUpdate(sdi3_204.Cli_NET.SeatsService.application[] arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="seatsToUpdateResponse", WrapperNamespace="http://ejb.impl.business.sdi.uo/", IsWrapped=true)]
    public partial class seatsToUpdateResponse {
        
        public seatsToUpdateResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findApplicationByTrip", WrapperNamespace="http://ejb.impl.business.sdi.uo/", IsWrapped=true)]
    public partial class findApplicationByTrip {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ejb.impl.business.sdi.uo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        public findApplicationByTrip() {
        }
        
        public findApplicationByTrip(long arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findApplicationByTripResponse", WrapperNamespace="http://ejb.impl.business.sdi.uo/", IsWrapped=true)]
    public partial class findApplicationByTripResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ejb.impl.business.sdi.uo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public sdi3_204.Cli_NET.SeatsService.application[] @return;
        
        public findApplicationByTripResponse() {
        }
        
        public findApplicationByTripResponse(sdi3_204.Cli_NET.SeatsService.application[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findApplication", WrapperNamespace="http://ejb.impl.business.sdi.uo/", IsWrapped=true)]
    public partial class findApplication {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ejb.impl.business.sdi.uo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ejb.impl.business.sdi.uo/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg1;
        
        public findApplication() {
        }
        
        public findApplication(long arg0, long arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findApplicationResponse", WrapperNamespace="http://ejb.impl.business.sdi.uo/", IsWrapped=true)]
    public partial class findApplicationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ejb.impl.business.sdi.uo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public sdi3_204.Cli_NET.SeatsService.application @return;
        
        public findApplicationResponse() {
        }
        
        public findApplicationResponse(sdi3_204.Cli_NET.SeatsService.application @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="request", WrapperNamespace="http://ejb.impl.business.sdi.uo/", IsWrapped=true)]
    public partial class request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ejb.impl.business.sdi.uo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ejb.impl.business.sdi.uo/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg1;
        
        public request() {
        }
        
        public request(long arg0, long arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="requestResponse", WrapperNamespace="http://ejb.impl.business.sdi.uo/", IsWrapped=true)]
    public partial class requestResponse {
        
        public requestResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findByUserAndTrip", WrapperNamespace="http://ejb.impl.business.sdi.uo/", IsWrapped=true)]
    public partial class findByUserAndTrip {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ejb.impl.business.sdi.uo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ejb.impl.business.sdi.uo/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg1;
        
        public findByUserAndTrip() {
        }
        
        public findByUserAndTrip(long arg0, long arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findByUserAndTripResponse", WrapperNamespace="http://ejb.impl.business.sdi.uo/", IsWrapped=true)]
    public partial class findByUserAndTripResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ejb.impl.business.sdi.uo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public sdi3_204.Cli_NET.SeatsService.seat @return;
        
        public findByUserAndTripResponse() {
        }
        
        public findByUserAndTripResponse(sdi3_204.Cli_NET.SeatsService.seat @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SeatsServiceChannel : sdi3_204.Cli_NET.SeatsService.SeatsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SeatsServiceClient : System.ServiceModel.ClientBase<sdi3_204.Cli_NET.SeatsService.SeatsService>, sdi3_204.Cli_NET.SeatsService.SeatsService {
        
        public SeatsServiceClient() {
        }
        
        public SeatsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SeatsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SeatsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SeatsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sdi3_204.Cli_NET.SeatsService.cancelSeatResponse sdi3_204.Cli_NET.SeatsService.SeatsService.cancelSeat(sdi3_204.Cli_NET.SeatsService.cancelSeat request) {
            return base.Channel.cancelSeat(request);
        }
        
        public void cancelSeat(sdi3_204.Cli_NET.SeatsService.seat arg0) {
            sdi3_204.Cli_NET.SeatsService.cancelSeat inValue = new sdi3_204.Cli_NET.SeatsService.cancelSeat();
            inValue.arg0 = arg0;
            sdi3_204.Cli_NET.SeatsService.cancelSeatResponse retVal = ((sdi3_204.Cli_NET.SeatsService.SeatsService)(this)).cancelSeat(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sdi3_204.Cli_NET.SeatsService.findByTripResponse sdi3_204.Cli_NET.SeatsService.SeatsService.findByTrip(sdi3_204.Cli_NET.SeatsService.findByTrip request) {
            return base.Channel.findByTrip(request);
        }
        
        public sdi3_204.Cli_NET.SeatsService.seat[] findByTrip(long arg0) {
            sdi3_204.Cli_NET.SeatsService.findByTrip inValue = new sdi3_204.Cli_NET.SeatsService.findByTrip();
            inValue.arg0 = arg0;
            sdi3_204.Cli_NET.SeatsService.findByTripResponse retVal = ((sdi3_204.Cli_NET.SeatsService.SeatsService)(this)).findByTrip(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sdi3_204.Cli_NET.SeatsService.seatsToUpdateResponse sdi3_204.Cli_NET.SeatsService.SeatsService.seatsToUpdate(sdi3_204.Cli_NET.SeatsService.seatsToUpdate request) {
            return base.Channel.seatsToUpdate(request);
        }
        
        public void seatsToUpdate(sdi3_204.Cli_NET.SeatsService.application[] arg0) {
            sdi3_204.Cli_NET.SeatsService.seatsToUpdate inValue = new sdi3_204.Cli_NET.SeatsService.seatsToUpdate();
            inValue.arg0 = arg0;
            sdi3_204.Cli_NET.SeatsService.seatsToUpdateResponse retVal = ((sdi3_204.Cli_NET.SeatsService.SeatsService)(this)).seatsToUpdate(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sdi3_204.Cli_NET.SeatsService.findApplicationByTripResponse sdi3_204.Cli_NET.SeatsService.SeatsService.findApplicationByTrip(sdi3_204.Cli_NET.SeatsService.findApplicationByTrip request) {
            return base.Channel.findApplicationByTrip(request);
        }
        
        public sdi3_204.Cli_NET.SeatsService.application[] findApplicationByTrip(long arg0) {
            sdi3_204.Cli_NET.SeatsService.findApplicationByTrip inValue = new sdi3_204.Cli_NET.SeatsService.findApplicationByTrip();
            inValue.arg0 = arg0;
            sdi3_204.Cli_NET.SeatsService.findApplicationByTripResponse retVal = ((sdi3_204.Cli_NET.SeatsService.SeatsService)(this)).findApplicationByTrip(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sdi3_204.Cli_NET.SeatsService.findApplicationResponse sdi3_204.Cli_NET.SeatsService.SeatsService.findApplication(sdi3_204.Cli_NET.SeatsService.findApplication request) {
            return base.Channel.findApplication(request);
        }
        
        public sdi3_204.Cli_NET.SeatsService.application findApplication(long arg0, long arg1) {
            sdi3_204.Cli_NET.SeatsService.findApplication inValue = new sdi3_204.Cli_NET.SeatsService.findApplication();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            sdi3_204.Cli_NET.SeatsService.findApplicationResponse retVal = ((sdi3_204.Cli_NET.SeatsService.SeatsService)(this)).findApplication(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sdi3_204.Cli_NET.SeatsService.requestResponse sdi3_204.Cli_NET.SeatsService.SeatsService.request(sdi3_204.Cli_NET.SeatsService.request request) {
            return base.Channel.request(request);
        }
        
        public void request(long arg0, long arg1) {
            sdi3_204.Cli_NET.SeatsService.request inValue = new sdi3_204.Cli_NET.SeatsService.request();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            sdi3_204.Cli_NET.SeatsService.requestResponse retVal = ((sdi3_204.Cli_NET.SeatsService.SeatsService)(this)).request(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sdi3_204.Cli_NET.SeatsService.findByUserAndTripResponse sdi3_204.Cli_NET.SeatsService.SeatsService.findByUserAndTrip(sdi3_204.Cli_NET.SeatsService.findByUserAndTrip request) {
            return base.Channel.findByUserAndTrip(request);
        }
        
        public sdi3_204.Cli_NET.SeatsService.seat findByUserAndTrip(long arg0, long arg1) {
            sdi3_204.Cli_NET.SeatsService.findByUserAndTrip inValue = new sdi3_204.Cli_NET.SeatsService.findByUserAndTrip();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            sdi3_204.Cli_NET.SeatsService.findByUserAndTripResponse retVal = ((sdi3_204.Cli_NET.SeatsService.SeatsService)(this)).findByUserAndTrip(inValue);
            return retVal.@return;
        }
    }
}
